---
baseurl: /
url: http://torch.ch
name: Torch
title: Torch
relative_permalinks: false
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
description: Scientific Computing for LuaJIT
timezone: America/Los_Angeles

safe: true
lsi: false
highlighter: pygments
