matrix:
    include:
        - os: linux
          dist: precise
          sudo: required
        - os: linux
          dist: trusty
          sudo: required
        - os: osx

script: ./install-deps
