name: Fetch Repositories

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

jobs:
  fetch-repos:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch repository list from elizaOS organization
      run: |
        curl -s https://api.github.com/orgs/elizaOS/repos?per_page=100 | jq -r '.[].name' > repo_list.txt

    - name: Upload repo_list.txt
      uses: actions/upload-artifact@v4
      with:
        name: repo_list
        path: repo_list.txt
